### ISSUE TITLE
Wrong query if `__args` is empty object

### ISSUE THREAD

**Issue by DblK** [vkolgi/json-to-graphql-query#19]
Hi,

I used this project to generated graphql query based on the json I passed.
I initialise a variable `args` to `{}` and then and properties depending on conditions.

However if none are match then the properties `__args = {}` and it's translated to `()` which leads to a fail.

Can you add a control on args to ensure that it's an objects with properties and in case of empty object it handles as there is no args.

Thx.

**Comment by dupski** [comment]
Yep totally will take a look at that at some point, otherwise sounds like an easy PR.... :)

**Comment by abdullah2993** [comment]
@dupski raised a PR for the fix
