### ISSUE TITLE
Content of 2.1.0 version does not contain the code from 'master'

### ISSUE THREAD

**Issue by paleika** [vkolgi/json-to-graphql-query#32]
Hello!

I'm using your lib to generate qraphql queries from the object and I've run into the #19 issue. I've found that it was solved via #27 but it was still reproducing.

While investigating I've run into the needed line of code in `src/jsonToGraphQLQuery.ts` and it version in node_modules differs from master branch although the version in package.json of the lib is 2.1.0

Can you please check if the right version of the package was published? Thanks.

**Note:** I use yarn 1.22.17 to manage dependencies

**Comment by vkolgi** [comment]
Hey @paleika,
I checked with the version 2.1.0 and I cannot reproduce the issue. 
I also confirmed that the test that we have passes which addresses the issue.
Is it possible to post the snippet or the graphql query which is failing for you.

**Comment by vkolgi** [comment]
Closing this issue as this is idle and no response from the OP.
