### ISSUE TITLE
Documentation is missing a mutation example

### ISSUE THREAD

**Issue by Bernold1** [vkolgi/json-to-graphql-query#54]
As the title states, we have no example on how to create a mutation, which could be super beneficial for everyone. 👍

**Comment by pheuberger** [comment]
Would love to see that as well. Also, it would be cool to have an example how to insert multiple objects for example. I'm not sure how the syntax for that would look like.

**Comment by vkolgi** [comment]
@Bernold1 The documentation for a simple mutation is added now. If you see the tests we do have another example as well.

**Comment by pheuberger** [comment]
thanks, @vkolgi! is it actually possible to insert multiple items at once?

**Comment by Bernold1** [comment]
Awesome thanks @vkolagi
